version: '3'
services:
  db:
    image: postgres:11
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=app_development
      - POSTGRES_PASSWORD=mysecretpassword
  redis:
    image: redis:4
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/opt/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_PASSWORD=mysecretpassword
