apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appName }}-secrets
  labels:
    app: {{ .Values.appName }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    environment: {{ .Values.global.environment }}
type: Opaque
data:
  DATABASE_PASSWORD: {{ .Values.global.DATABASE_PASSWORD | b64enc | quote }}
  {{- if .Values.global.gcpServiceAccountKey }}
  credentials.json: {{ .Values.global.gcpServiceAccountKey | b64enc | quote }}
  {{- end }}
  SECRET_KEY_BASE: {{ .Values.secret_key_base | b64enc | quote }}

