steps:

  - id: 'pull-db'
    name: 'gcr.io/cloud-builders/docker'
    args:
    entrypoint: bash
    args:
      - -c
      - |
        docker pull postgres:11
    waitFor: ['-']

  - id: 'pull-redis'
    name: 'gcr.io/cloud-builders/docker'
    args:
    entrypoint: bash
    args:
      - -c
      - |
        docker pull redis:4
    waitFor: ['-']

  - id: build-test-image
    name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -c
      - |
        docker image build --build-arg bundle_without="development" --build-arg rails_env="production" -t gcr.io/${PROJECT_ID}/rails-test:${COMMIT_SHA} .
    waitFor: ['-']

images:
  - gcr.io/${PROJECT_ID}/rails-test:${COMMIT_SHA}
