apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}-config
  labels:
    app: {{ .Values.appName }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    environment: {{ .Values.global.environment }}
data:
  POSTGRES_DB: {{ .Values.global.DATABASE_NAME }}
  POSTGRES_USER: {{ .Values.global.DATABASE_USERNAME }}
