apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
spec:
  # we want the app to be highly-available
  replicas: 2

  selector:
    matchLabels:
        app: {{ .Values.appName }}
        component: database
        release: {{ .Release.Name }}

  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}

      labels:
        app: {{ .Values.appName }}
        heritage: {{ .Release.Service }}
        release: {{ .Release.Name }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version }}
        environment: {{ .Values.global.environment }}
        component: database

    spec:
      containers:
      - name: {{ .Values.appName }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        command: ["/cloud_sql_proxy",
                  "-instances={{ .Values.gcpProject }}:{{ .Values.gcpRegion }}:{{ .Values.cloudSQLInstanceName }}=tcp:0.0.0.0:{{ .Values.global.POSTGRESQL_PORT_NUMBER }}",
                  "-credential_file=/secrets/cloudsql/credentials.json"]

        securityContext:
          runAsUser: 2  # non-root user
          allowPrivilegeEscalation: false

        livenessProbe:
          tcpSocket:
            port: {{ .Values.global.POSTGRESQL_PORT_NUMBER }}
          initialDelaySeconds: 60
        readinessProbe:
          tcpSocket:
            port: {{ .Values.global.POSTGRESQL_PORT_NUMBER }}
          initialDelaySeconds: 10

        ports:
          - name: db-port
            containerPort: {{ .Values.global.POSTGRESQL_PORT_NUMBER }}

        resources:
          requests:
            cpu: 50m
            memory: 10Mi

        volumeMounts:
          - name: {{ .Values.appName }}-credentials
            mountPath: /secrets/cloudsql
            readOnly: true

      volumes:
        - name: {{ .Values.appName }}-credentials
          secret:
            secretName: {{ .Values.appName }}-credentials
