apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appName }}-credentials
  labels:
    app: {{ .Values.appName }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    environment: {{ .Values.global.environment }}
type: Opaque
data:
  credentials.json: {{ .Values.global.gcpServiceAccountKey | b64enc | quote }}
